correctas = int(input("Número de respuestas correctas: "))
incorrectas = int(input("Número de respuestas incorrectas: "))
blanco = int(input("Número de respuestas en blanco: "))
puntaje = (correctas * 5) + (incorrectas * -1) + (blanco * 0)
print(f"Puntaje obtenido: {puntaje}")